### Задание 1. Создать numpy array с элементами от числа N до 0

In [1]:
import numpy as np

In [2]:
# Вариант один: генерация массива с помощью отрицательного шага
n = 10
np.arange(n-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
# Вариант два:реверс элементов массива
n = 10
np.flip(np.arange(0, n))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2. Создать диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

In [4]:
n = 10
x =np.diag(np.flip(np.arange(0, n)), k=0)     # Создание диагональной матрицы с убывающим порядком значений в диагонали
x

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
x.sum()        #сумма всех элементов объекта array

45

### 3. Решить систему уравнений:
              4x + 2y + z = 4
              x + 3y = 12
              5y + 4z = -3

In [6]:
from numpy import linalg

In [7]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [8]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4. Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. На сайт заходит очередной посетитель. Найти самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [10]:
vectors = {}
next_user_stats_len = np.linalg.norm(next_user_stats)
user_id = 1
for user in users_stats:
    user_len = np.linalg.norm(user)
    vectors['user' + str(user_id)] = np.dot(next_user_stats, user)/(next_user_stats_len * user_len)
    user_id +=1
max(vectors, key = lambda k: vectors[k])

'user8'